[project]
name = "indico-payment-opencollective"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.entry-points.'indico.plugins']
payment_opencollective = 'indico_payment_opencollective.plugin:OpenCollectivePaymentPlugin'