GQL_QUERY_RESULT_MOCK = {
    "order": {
        "id": "rxg0j35l-zkwm6vv8-lzx6voe9-8n47daby",
        "legacyId": 797048,
        "description": "Financial contribution to UbuCon Asia 2024",
        "amount": {"value": 10, "currency": "USD", "valueInCents": 1000},
        "taxAmount": None,
        "totalAmount": {"value": 10, "currency": "USD", "valueInCents": 1000},
        "quantity": 1,
        "status": "PAID",
        "frequency": "ONETIME",
        "nextChargeDate": None,
        "fromAccount": {
            "id": "5ax8emk7-lnw54q7b-oxopgyvj-0o93zdrb",
            "slug": "youngbin-han",
            "type": "INDIVIDUAL",
            "name": "Youngbin Han",
            "legalName": None,
            "description": None,
            "longDescription": None,
            "tags": None,
            "currency": "USD",
            "expensePolicy": None,
            "isIncognito": False,
            "createdAt": "2021-04-06T13:15:25.569Z",
            "updatedAt": "2024-10-08T06:14:18.063Z",
            "isArchived": False,
            "isFrozen": False,
            "isActive": False,
            "isHost": False,
            "isAdmin": False,
            "emails": None,
            "supportedExpenseTypes": ["INVOICE", "RECEIPT"],
            "categories": [],
        },
        "toAccount": {
            "id": "mlo94zn7-x08dpo0o-ajxpewga-3vjbrky5",
            "slug": "ubucon-asia-2024-d62e355c",
            "type": "EVENT",
            "name": "UbuCon Asia 2024",
            "legalName": None,
            "description": "Aug 31 - Sep 2, JECRC Foundation, Jaipur, India",
            "longDescription": None,
            "tags": None,
            "currency": "USD",
            "expensePolicy": None,
            "isIncognito": False,
            "createdAt": "2024-03-01T06:42:28.150Z",
            "updatedAt": "2024-09-26T02:13:37.416Z",
            "isArchived": False,
            "isFrozen": False,
            "isActive": True,
            "isHost": False,
            "isAdmin": False,
            "emails": None,
            "supportedExpenseTypes": ["INVOICE", "RECEIPT"],
            "categories": [],
        },
        "createdAt": "2024-10-08T14:36:30.043Z",
        "updatedAt": "2024-10-08T14:36:33.822Z",
        "totalDonations": {"value": 10, "currency": "USD", "valueInCents": 1000},
        "paymentMethod": {
            "id": "gnxdwzj3-le5mpwzx-nnvpy8rv-bko04a97",
            "legacyId": 777761,
            "name": None,
            "service": "STRIPE",
            "type": "CREDITCARD",
            "data": None,
            "expiryDate": None,
            "createdAt": "2024-01-22T14:03:16.050Z",
        },
        "hostFeePercent": 10,
        "platformTipAmount": {"value": 0, "currency": "USD", "valueInCents": 0},
        "platformTipEligible": False,
        "tags": [],
        "tax": None,
        "activities": {"offset": 0, "limit": 3, "totalCount": 3},
        "data": {},
        "customData": None,
        "memo": None,
        "processedAt": "2024-10-08T14:36:33.822Z",
        "pendingContributionData": None,
        "needsConfirmation": None,
        "comments": None,
    }
}
