name: CD

on:
  push:
    tags:
      - "v*.*.*"
env:
  PYTHON_VERSION: '3.12'

jobs:
  release:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Setup and Activate virtualenv
        run: |
          uv venv venv --python ${{ env.PYTHON_VERSION }}
          source venv/bin/activate
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
          echo "$(pwd)/venv/bin" >> $GITHUB_PATH
      
      - name: Install system dependencies
        run: sudo apt-get install postgresql-client libpq-dev redis-server
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
  
      - name: Install Indico
        run: |
          uv pip install -U pip setuptools wheel
          uv pip install Babel
          uv pip install "indico[dev] @ git+https://github.com/indico/indico.git"
      
      - name: Build wheel
        run:  uv build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            *.tar.gz
